name: Playwright SpecFlow Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright/dotnet:v1.48.0-noble

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - name: Run your tests
        run: dotnet test
